version: 2.1

orbs:
  codecov: codecov/codecov@1.0.3

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - v1-yarn-packages-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          name: Save yarn package cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test:ci
      - store_test_results:
          path: test-results
      # The following two steps are done in Travis CI
      # - run:
      #     name: Run coverage
      #     command: yarn coveralls
      # - codecov/upload:
      #     file: coverage/coverage-final.json
      - run:
          name: Run build
          command: yarn build

workflows:
  version: 2
  test:
    jobs:
      - test
