import { MutationResolvers } from '../../types';
import { UserMutations } from './User/UserMutations';

// MutationResolvers.Type is generated by `graphqlgen`.
export const Mutation: MutationResolvers.Type = {
  ...MutationResolvers.defaultResolvers,
  ...UserMutations,
};
