import { QueryResolvers } from '../../types';
import { UserQueries } from './User/UserQueries';
import { ServerDiagnosticsQueries } from './ServerDiagnostics/ServerDiagnosticsQueries';

// QueryResolvers.Type is generated by `graphqlgen`.
export const Query: QueryResolvers.Type = {
  ...QueryResolvers.defaultResolvers,
  ...ServerDiagnosticsQueries,
  ...UserQueries,
};
