import {
  QueryResolvers,
  MutationResolvers,
  SubscriptionResolvers,
} from '../../../types';

/**
 * These interfaces are a subset of the types generated by `graphqlgen`.
 * Extend the resolvers required for the User model by using Typescript's
 * `Pick` interface to select the methods that should be extended.
 */

interface IUserQueries
  extends Pick<QueryResolvers.Type, 'user'>,
    Pick<QueryResolvers.Type, 'users'>,
    Pick<QueryResolvers.Type, 'expensiveUsers'> {}

interface IUserMutations
  extends Pick<MutationResolvers.Type, 'addUser'>,
    Pick<MutationResolvers.Type, 'deleteUser'> {}

interface IUserSubscriptions
  extends Pick<SubscriptionResolvers.Type, 'newUser'> {}
